minio.url=${MINIO_URL:http://localhost}:${MINIO_PORT:9000}
minio.username=${MINIO_USERNAME:minioadmin}
minio.password=${MINIO_PASSWORD:minioadmin}
minio.bucket.name.company-documents=${BUCKET_COMPANY_DOCUMENTS:company-documents}
minio.bucket.name.declaration-documents=${BUCKET_DECLARATIONS:declaration-documents}
minio.bucket.name.signatures=${BUCKET_SIGNATURES:signatures}
bucket.name.photo-profile=${BUCKET_PHOTO_PROFILE:photo-profile}

