minio.url=${MINIO_URL:http://localhost}:${MINIO_PORT:9000}
minio.username=${MINIO_USERNAME:minioadmin}
minio.password=${MINIO_PASSWORD:minioadmin}
minio.bucket.name.company-documents
minio.bucket.name.individual-documents
minio.bucket.name.declaration-documents
