@auth_token = eyJhbGciOiJIUzUxMiJ9.eyJtYWlsIjoiZGF1dG92LjI5MjAwOUBnbWFpbC5jb20iLCJwaG9uZSI6IjAyMjA0NDIzNDIzNCIsInVzZXJuYW1lIjoiZGF1dG92LjI5MjAwOUBnbWFpbC5jb20iLCJzdWIiOiJkYXV0b3YuMjkyMDA5QGdtYWlsLmNvbSIsImlhdCI6MTc3MDIxNzk5MCwiZXhwIjoxNzcwMjE4MTEwfQ.4FE39DlIf3rg667YXluHDF2sIkz_s5HLzBfjNF-FrNuYpyHSxa5epzJ92cvYLwJQWPWNk3Sq69KfjTh9rEiutQ

###

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "user_1",
  "mail": "user_1@gmail.com",
  "phone": "022044234234",
  "password": "qweqwe",
  "roleName": "USER"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email": "dautov.292009@gmail.com",
  "password": "chert123"
}

###


POST http://localhost:8080/api/auth/refresh-token
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJtYWlsIjoiZGF1dG92LjI5MjAwOUBnbWFpbC5jb20iLCJpZCI6MTAsInN1YiI6ImRhdXRvdi4yOTIwMDlAZ21haWwuY29tIiwiaWF0IjoxNzcwMjE3OTg2LCJleHAiOjE3NzA4MjI3ODZ9.cd2gqvyAT7Vmcrq9HKt9hOTj40bLXUfQXpTsnVwoZZUB0kcaUjSXQ4acoZLO8LjKgskeA9n5SraiLYoCk7w0PA


###
POST http://localhost:8080/api/auth/password-recovery?
    email=nurdann2203@gmail.com
Accept-Language: kg


###
POST http://localhost:8080/api/auth/reset-password?
    code=358608
Content-Type: application/json

{
  "newPassword": "nurdan",
  "confirmPassword": "nurdan"
}

